# Generated by Django 5.0.1 on 2024-01-15 16:25

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=100, verbose_name='ename')),
                ('ephone', models.CharField(max_length=15, validators=[employees.models.validate_ephone], verbose_name='ephone')),
                ('eemail', models.CharField(max_length=100, verbose_name='eemail')),
                ('edepartment', models.CharField(max_length=20, verbose_name='edepartment')),
            ],
        ),
    ]
